# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2890f64afa326fb0366c004cbf4e9710b864a22326c426c79ac189ca47acc6abf38be8c8b37cda82dd37b8b4686027234ab2fd957368666574f6a288d45261d5

test:
  secret_key_base: c2d0c439534bdd19e382a24b07f52641321e488704303a0e7d203c56bf1bd572ded4d25cd387aec06d77515cbd5c29d424dd2c1394d0e3a26331c03c085217d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
